### ISSUE TITLE
Major CHI milestones

### ISSUE THREAD

**Issue by AbeHandler** [fortytw0/needfinder#15]
**Coding and automatic evaluation**

- [ ] Get arora/sbert running on CURC so we can run experiments, experiment w/ hyperparam settings like glove/w2v/embedding size etc.

- [ ] Auto eval 
   - [ ] Decide on tuning procedures/hypermaram choices for transformer-based model 
   - [ ] implement them
   - [ ] write them down/explain and justify 
   - [ ] https://github.com/fortytw0/needfinder/issues/14

** Human evaluation**
- [ ] Based on autoeval, do human eval https://github.com/fortytw0/needfinder/issues/3

** Writing and feedback**
- [ ] Write up everything by maybe mid August so we have weeks to edit and get feedback
